[book]
title = "Arcadia Documentation"
authors = ["Arcadia-Solutions Team"]
language = "en"
src = "src"

[output.html]
default-theme = "dark"
git-repository-url = "https://github.com/Arcadia-Solutions/arcadia"
